print("Coding challenge")
print("Still running updates")
print("Starting to prefer Linux over Windows")
print("Too much updates and they slow down a Windows Machine")
print("Really getting displeased with Windows")
